### ISSUE TITLE
ROSC drive stages error in datasheet

### ISSUE THREAD

**Issue by pm-mic** [raspberrypi/pico-feedback#257] opened 2022-07-12 13:03 UTC
There's an error in the RP2040 datasheet in section 2.17.3, it indicates that the ROSC HIGH setting uses drive stages 0-3. However, changing these does not alter the frequency, changing 4-7 does!

**Comment by aallan** [comment] 2024-01-22 19:52
Confirmed. Will get updated in the next documentation update.

Section 2.17.3 "Modifying the frequency" will now read…

> The frequency range is changed by writing to the FREQ_RANGE register which controls the number of stages in the ROSC loop. The default LOW range has 8 (stages 0-7), MEDIUM has 6 (stages 2-7), HIGH has 4 (stages 4-7) and TOOHIGH has 2 (stages 6-7).

While the description of the ROSC: CTRL Register will be changed to be…

> Controls the number of delay stages in the ROSC ring 
> LOW uses stages 0 to 7 
> MEDIUM uses stages 2 to 7 
> HIGH uses stages 4 to 7 
> TOOHIGH uses stages 6 to 7 and should not be used because its frequency exceeds design specifications

**Comment by nathan-contino** [comment] 2024-01-24 20:28
Closing since this has been completed and will go out shortly.

**Closed as completed by nathan-contino** 2024-01-24 20:28 UTC
Labels: documentation, rp2040, pdf
