### ISSUE TITLE
Bold and italic text in doxygen comments not appearing in SDK PDF

### ISSUE THREAD

**Issue by smithps** [raspberrypi/pico-feedback#151] opened 2021-04-30 13:23 UTC
I wish to report an error in the Pi Pico manual. 

Manual: Raspberry Pi Pico C/C++ SDK Release 1.4.1      

The same Typo error is on Page 200 and 201      

The phrase:    
...then true will be returned and the calling core will own the mutex, otherwise false will be returned and the calling core will own the mutex.      

Should read:    
...then true will be returned and the calling core will own the mutex,   otherwise false will be returned and the calling core will *not* own the   mutex.

Looks like a cut and paste of the first typo.

**Comment by lurch** [comment] 2021-04-30 15:09
This text comes from the doxygen-comments in the SDK, and it's correct at https://raspberrypi.github.io/pico-sdk-doxygen/group__mutex.html#ga69e2f75f0a38378b20c0f2bf9cc7bbe3 and also correct when I _locally_ build `raspberry-pi-pico-c-sdk.pdf`, but incorrect at https://datasheets.raspberrypi.org/pico/raspberry-pi-pico-c-sdk.pdf :confused: 
Very strange, currently investigating...

**Comment by lurch** [comment] 2021-05-04 09:36
The "works for me when I locally build" was actually a red-herring caused by accidental doxygen-version mismatches (I **can** now reproduce this myself). I've tracked down the problem to a bug in our XSLT-processing pipeline...

**Comment by aallan** [comment] 2021-05-25 10:53
@lurch Did this get resolved, or is it in backlog?

**Comment by lurch** [comment] 2021-05-25 11:08
In backlog, is a problem with my XSLT.

**Comment by lurch** [comment] 2022-06-16 12:46
The bug here was that the "not" in "the calling core will not own the mutex" was inside asterisks to make it **bold**, but a bug in my XSLT meant that bold-text wasn't getting included in the PDF output. Whoops!

I can't remember if I fixed that particular XSLT bug (probably not?) but in the meantime @kilograham changed the doxygen-comment (in pico-sdk 1.3.0) to take out the asterisks, so https://datasheets.raspberrypi.org/pico/raspberry-pi-pico-c-sdk.pdf _already_ correctly says "Otherwise (if the mutex was already owned) this will return false and the caller will NOT own the mutex."

So the original issue has been solved, but I'll leave this open to remind myself to fix bold-text in Doxygen output in case this ever occurs again.

**Comment by lurch** [comment] 2022-06-18 23:01
I've just spotted another place where this is tripping up: In the [HTML version](https://raspberrypi.github.io/pico-sdk-doxygen/group__sleep.html#gaedc0ed51a5e908ddd660a5d279009abc) of the SDK docs, `best_effort_wfe_or_timeout` correctly says "This is called _best_effort_ because ..." (note that 'best_effort' is displayed in italics), but in the [PDF version](https://datasheets.raspberrypi.com/pico/raspberry-pi-pico-c-sdk.pdf) of the SDK docs, the same string reads as "This is called because ..." (note that 'best_effort' has been omitted entirely - oops).

**Comment by kilograham** [comment] 2022-06-18 23:41
Yeah, maybe we can bump this in priority :-)

**Comment by lurch** [comment] 2022-12-02 16:54
Closing as invalid, as the SDK API docs are now only at https://raspberrypi.github.io/pico-sdk-doxygen/ and no longer included in the C-SDK PDF.

**Closed as completed by lurch** 2022-12-02 16:54 UTC
Labels: documentation, invalid, infrastructure
