### ISSUE TITLE
As a new user 

### ISSUE THREAD

**Issue by petercwallis** [raspberrypi/pico-feedback#254] opened 2022-07-04 09:31 UTC
Chapter 3 of the "getting started with Raspberry Pi Pico" does blink a LED; Chapter 8 says how to set up your own project.

The provided examples do not follow the instructions in chapter 8.

I'd suggest that Chapter 3 be rewritten to extract the example of blink.c from those on the distribution and run it.

**Comment by aallan** [comment] 2022-07-04 13:41
Duplicate of #251

**Closed as completed by aallan** 2022-07-04 13:41 UTC
Labels: duplicate
