### ISSUE TITLE
GP19 always high when set as output

### ISSUE THREAD

**Issue by toetlinger** [raspberrypi/pico-feedback#40] opened 2021-01-30 22:13 UTC
GP19 is immediately going high when set as output (Pin.OUT).
Setting to low (.value(0)) has no effect.
GP19 appears to function properly when set as input (Pin.IN).
All other GP pins appear to function normally.
I have 5 Pico's. All exhibit the same behavior.
I'm using pico_micropython_20210121.uf2

**Comment by lurch** [comment] 2021-01-30 23:24
Duplicate of https://github.com/raspberrypi/pico-micropython-examples/issues/7
(see that other issue for more info)

**Closed by lurch** 2021-01-30 23:24 UTC
