### ISSUE TITLE
nmake fail to compile from 2nd times

### ISSUE THREAD

**Issue by brtchip-tuannguyen** [raspberrypi/pico-feedback#111] opened 2021-03-03 03:12 UTC
On window, after compiled blink example successful, nmake return error when run again:

![image](https://user-images.githubusercontent.com/48436368/109746371-dbd95200-7c07-11eb-8dba-39c828b99ff1.png)

Look at the compiler_depend.make and see that some locations are modified to incorrect string: Some location start with "D:\\" were changed to "D\\:"

![image](https://user-images.githubusercontent.com/48436368/109746553-265ace80-7c08-11eb-9584-da6efe8257fe.png)

There is a work around to compile, that is correct the location in compiler_depend.make (with notepad/vim...etc), then run nmake.

This issue happens on VScode too.

**Comment by lurch** [comment] 2021-03-03 11:45
Duplicate of https://github.com/raspberrypi/pico-sdk/issues/169 ?  What version of CMake do you have installed?

**Comment by brtchip-tuannguyen** [comment] 2021-03-04 03:58
> What version of CMake do you have installed?

I using cmake version 3.20.0-rc2

**Comment by lurch** [comment] 2021-03-04 08:34
As I explained in that issue I linked to (and as also explained in section 9.2.1.2. of https://datasheets.raspberrypi.org/pico/getting-started-with-pico.pdf) there seems to be a bug in that version of CMake. Please uninstall it and try using CMake 3.19.6 instead.

**Closed as completed** 2021-03-04 08:54 UTC
Labels: duplicate, c/c++ sdk, windows

**Comment by aallan** [comment] 2021-03-29 12:05
Reported upstream as a CMake bug, https://gitlab.kitware.com/cmake/cmake/-/issues/21997, by @lurch.

**Comment by lurch** [comment] 2021-04-12 09:19
FYI this is now fixed in [CMake 3.20.1](https://cmake.org/download/) :tada:

**Comment by aallan** [comment] 2021-04-12 09:34
> FYI this is now fixed in [CMake 3.20.1](https://cmake.org/download/) 🎉

@lurch Can you update the NOTE block in the PDF documentation to indicate that, we should leave the warning in as there will be versions of CMake floating around which are broken in this regard for a long time, but the exact wording now needs updating I think.
