### ISSUE TITLE
Typo in table for `pico_set_float_implementation`.

### ISSUE THREAD

**Issue by asynts** [raspberrypi/pico-feedback#102] opened 2021-02-21 12:46 UTC
In the ["Raspberry Pi Pico C/C++ SDK"][1] PDF there is a table in section 2.7.2.3 "Configuration and alternate implementations" which shows the avaliable options for `pico_set_float_implementation` this table contains the entry "pico" twice, the second one should be "none".

![image](https://user-images.githubusercontent.com/31994781/108625427-2fe77800-744b-11eb-9bfa-0aa8a0bd65cb.png)

  [1]: https://datasheets.raspberrypi.org/pico/raspberry-pi-pico-c-sdk.pdf

**Comment by lurch** [comment] 2021-02-21 13:05
Duplicate of #92

**Closed by lurch** 2021-02-21 13:05 UTC
