### ISSUE TITLE
SDK-Documentation: Missing return in int main()

### ISSUE THREAD

**Issue by pingufreak** [raspberrypi/pico-feedback#282] opened 2022-10-15 16:11 UTC
As in the subject, the examples doesn't return an int. But I think it's important, because I had issues with the usb-serial if not returning int.

**Comment by lurch** [comment] 2022-10-15 18:35
_Very_ little detail in this issue, but I believe it relates to https://github.com/raspberrypi/pico-feedback/issues/283 ?

**Comment by aallan** [comment] 2022-10-16 10:27
Duplicate of #283

**Closed as completed by aallan** 2022-10-16 10:27 UTC
Labels: documentation, duplicate

**Comment by aallan** [comment] 2022-11-05 18:50
If you have more information to add to this, please add it to #283.
